<% environments.forEach(function(env) { %>
<%= env %>:
  theme-id: (optional - if empty, you will write to the active theme)
  password: XXXXXXXXXX
  store: my-store-name.myshopify.com
<% }); %>
  ignore_files:
    - config/settings.html
    - "*.png"
    - "*.jpg"
